apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mysecretbox
    literals:
      - u=juhisinha
      - p=juhisinha123
resources:
- mysql_deployment.yml
- wordpress_deployment.yml
