apiVersion: v1
data:
  p: cmVkaGF0
  u: aGltYW5zaHU=
kind: Secret
metadata:
  creationTimestamp: "2025-04-15T10:00:10Z"
  name: mysecretbox
  namespace: default
  resourceVersion: "1482"
  uid: 6f7f0dbc-faaa-425d-9fd2-531d072a761d
type: Opaque
